# -*- Mode: Python -*-

Import('freestanding_env')

fenv = freestanding_env.Clone()

fenv['CPPPATH'] = ["#include", "include/"]
fenv['LINKFLAGS'] += " -T standalone/morbo.ld" 

cutil = fenv.StaticLibrary('cutil',
                           [ 'strncpy.c',
                             'strtok.c',
                             'strtol.c',
                             'strtoll.c',
                             ])

rom_unfixed = fenv.Command('option-rom.bin-unfixed', 'option-rom.asm', "yasm -f bin -o $TARGET $SOURCE")
rom = fenv.Command('option-rom.bin', rom_unfixed, "./bin/rom_fixup.py $SOURCE $TARGET")

final = fenv.Program('morbo',
                     ['start.asm',
                      'cpuid.asm',
                      'crc16.c',
                      'util.c',
                      'elf.c',
                      'reboot.c',
                      'pci.c',
                      'pci_db.c',
                      'printf.c',
                      'main.c',
                      'version.c',
                      'serial.c',
                      'ohci.c',
                      'apic.c',
                      ],
                     LIBS=['cutil'],
                     LIBPATH=['.']
                     )

Depends(final, 'morbo.ld')

Install('#tftp', [ final ])
# EOF
