# -*- Mode: Python -*-

env = Environment()

env['CXXFLAGS'] = "-std=c++0x -g"
env['CPPPATH'] = ["include/"]

env.Library('brimstone2', ['brimstone2.cpp'])
env.Program('test_brimstone2', ['test_brimstone2.cpp'], LIBPATH='.', LIBS=['brimstone2'])

# EOF
