# -*- Mode: Python -*-

env = Environment()

env['CXXFLAGS'] = "-std=c++0x -g -O0"
env['CPPPATH'] = ["include/"]

env.Library('brimstone', ['brimstone.cpp'])
env.Program('test_brimstone', ['test_brimstone.cpp'], LIBPATH='.', LIBS=['brimstone'])

# EOF
